/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appone;

import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author Udom
 */
public final class StudentMyProfile extends javax.swing.JFrame {
    String pk;
        
    /**
     * Creates new form StudentMyProfile
     */
    public StudentMyProfile() {
        initComponents();
        MyDp();
        setBackground(new Color(0,0,0,0));
        viewpaN.setEnabled(false);
        viewpaN.setVisible(false);
        set0.setEnabled(false);
        set0.setVisible(false);
    }
   void  MyDp(){
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JLabel();
        ViewCourseWork = new javax.swing.JLabel();
        MyProfile = new javax.swing.JLabel();
        ChangePass = new javax.swing.JLabel();
        set1 = new javax.swing.JLabel();
        set0 = new javax.swing.JLabel();
        viewpaN = new javax.swing.JPanel();
        LogOut = new javax.swing.JLabel();
        MyProFile = new javax.swing.JLabel();
        ChangePass1 = new javax.swing.JLabel();
        viewSetting1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDCAPTURE = new javax.swing.JLabel();
        First = new javax.swing.JLabel();
        NAMEFIRST = new javax.swing.JLabel();
        Last = new javax.swing.JLabel();
        NAMELAST = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        NAMEID = new javax.swing.JLabel();
        FacuLty = new javax.swing.JLabel();
        NAMEFACULTY = new javax.swing.JLabel();
        GendR = new javax.swing.JLabel();
        NAMEGENDER = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        NAMEPHONE = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        NAMEMAIL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 95, 20));

        ViewCourseWork.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewCourseWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewCourseWorkMouseClicked(evt);
            }
        });
        getContentPane().add(ViewCourseWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 288, 130, 20));

        MyProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyProfileMouseClicked(evt);
            }
        });
        getContentPane().add(MyProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 314, 100, 20));

        ChangePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChangePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePassMouseClicked(evt);
            }
        });
        getContentPane().add(ChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 346, 140, 20));

        set1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        set1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                set1MouseClicked(evt);
            }
        });
        getContentPane().add(set1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 32, 30));

        set0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                set0MouseClicked(evt);
            }
        });
        getContentPane().add(set0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 32, 30));

        viewpaN.setBackground(new java.awt.Color(42, 101, 106));
        viewpaN.setLayout(null);

        LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });
        viewpaN.add(LogOut);
        LogOut.setBounds(20, 78, 80, 20);

        MyProFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyProFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyProFileMouseClicked(evt);
            }
        });
        viewpaN.add(MyProFile);
        MyProFile.setBounds(20, 17, 90, 20);

        ChangePass1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChangePass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePass1MouseClicked(evt);
            }
        });
        viewpaN.add(ChangePass1);
        ChangePass1.setBounds(20, 48, 140, 20);

        viewSetting1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appone/images/Group 2.png"))); // NOI18N
        viewpaN.add(viewSetting1);
        viewSetting1.setBounds(0, 0, 169, 118);

        getContentPane().add(viewpaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 367, 169, 118));

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 3, 30, 27));

        IDCAPTURE.setFont(new java.awt.Font("Merienda", 0, 14)); // NOI18N
        IDCAPTURE.setForeground(new java.awt.Color(255, 255, 255));
        IDCAPTURE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(IDCAPTURE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 160, 30));

        First.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        First.setText("FIRST NAME");
        getContentPane().add(First, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 90, 30));

        NAMEFIRST.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        getContentPane().add(NAMEFIRST, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 170, 30));

        Last.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Last.setText("LAST NAME");
        getContentPane().add(Last, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 90, 30));

        NAMELAST.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        getContentPane().add(NAMELAST, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 170, 30));

        ID.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        ID.setText("IDENTITY");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 90, 30));

        NAMEID.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        getContentPane().add(NAMEID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 170, 30));

        FacuLty.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        FacuLty.setText("PROGRAM");
        getContentPane().add(FacuLty, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 90, 30));

        NAMEFACULTY.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        getContentPane().add(NAMEFACULTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 170, 30));

        GendR.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        GendR.setText("GENDER");
        getContentPane().add(GendR, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 90, 30));

        NAMEGENDER.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        getContentPane().add(NAMEGENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 170, 30));

        Phone.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Phone.setText("PHONE ");
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 90, 30));

        NAMEPHONE.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        getContentPane().add(NAMEPHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 170, 30));

        Email.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Email.setText("EMAIL");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 90, 30));

        NAMEMAIL.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        getContentPane().add(NAMEMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appone/imagestudents/AppOneStudentMyProfile.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    for (double i=0.0; i<=1.0;i=i+0.1){
    String val=i+"";
    float f=Float.valueOf(val);
    this.setOpacity(f);
    try{
        Thread.sleep(50);
    }                                 

    catch(Exception e){
        
    }
   }           // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        StudentDashboard ez = new StudentDashboard();
          ez.setVisible(true);
           ez.su(pk);
           this.dispose();   
    }//GEN-LAST:event_homeMouseClicked

    private void ViewCourseWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewCourseWorkMouseClicked
        StudentViewCoursework ed = new StudentViewCoursework();
          ed.setVisible(true);
           ed.su(pk);
           this.dispose();
    }//GEN-LAST:event_ViewCourseWorkMouseClicked

    private void MyProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProfileMouseClicked
        StudentMyProfile ev = new StudentMyProfile();
          ev.setVisible(true);
           ev.su(pk);
           this.dispose();
    }//GEN-LAST:event_MyProfileMouseClicked

    private void ChangePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePassMouseClicked
        StudentChangePassword zv = new StudentChangePassword();
          zv.setVisible(true);
           zv.su(pk);
           this.dispose();
    }//GEN-LAST:event_ChangePassMouseClicked

    private void set1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set1MouseClicked
        viewpaN.setEnabled(true);
        viewpaN.setVisible(true);
        set0.setEnabled(true);
        set0.setVisible(true);
        set1.setEnabled(false);
        set1.setVisible(false);
    }//GEN-LAST:event_set1MouseClicked

    private void set0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set0MouseClicked
        viewpaN.setEnabled(false);
        viewpaN.setVisible(false);
        set0.setEnabled(false);
        set0.setVisible(false);
        set1.setEnabled(true);
        set1.setVisible(true);
    }//GEN-LAST:event_set0MouseClicked

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        new LogiN().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutMouseClicked

    private void MyProFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProFileMouseClicked
        StudentMyProfile uv = new StudentMyProfile();
          uv.setVisible(true);
           uv.su(pk);
           this.dispose();
    }//GEN-LAST:event_MyProFileMouseClicked

    private void ChangePass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePass1MouseClicked
        StudentChangePassword ziv = new StudentChangePassword();
          ziv.setVisible(true);
           ziv.su(pk);
           this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePass1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMyProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChangePass;
    private javax.swing.JLabel ChangePass1;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FacuLty;
    private javax.swing.JLabel First;
    private javax.swing.JLabel GendR;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel IDCAPTURE;
    private javax.swing.JLabel Last;
    private javax.swing.JLabel LogOut;
    private javax.swing.JLabel MyProFile;
    private javax.swing.JLabel MyProfile;
    private javax.swing.JLabel NAMEFACULTY;
    private javax.swing.JLabel NAMEFIRST;
    private javax.swing.JLabel NAMEGENDER;
    private javax.swing.JLabel NAMEID;
    private javax.swing.JLabel NAMELAST;
    private javax.swing.JLabel NAMEMAIL;
    private javax.swing.JLabel NAMEPHONE;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel ViewCourseWork;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel set0;
    private javax.swing.JLabel set1;
    private javax.swing.JLabel viewSetting1;
    private javax.swing.JPanel viewpaN;
    // End of variables declaration//GEN-END:variables

    final void su(String shaa) {
        pk = shaa;
        IDCAPTURE.setText(shaa);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/civesystem","root","");
            Statement st =con.createStatement();
            String sql;
            sql = "SELECT * FROM `student` WHERE ID='"+pk+"'";
            ResultSet rs=st.executeQuery(sql);
             while(rs.next()){
                String Fname=rs.getString("Fname");
                String Lname=rs.getString("Lname");
                String Id=rs.getString("ID");
                String facu=rs.getString("FACULTY");
                String Jinsia=rs.getString("GENDER");
                String des=rs.getString("PHONENUMBER");
                String mail=rs.getString("EMAIL");
                
                 NAMEFIRST.setText(Fname);
                 NAMELAST.setText(Lname);
                 NAMEID.setText(Id);
                 NAMEFACULTY.setText(facu);
                 NAMEGENDER.setText(Jinsia);
                 NAMEPHONE.setText(des);
                 NAMEMAIL.setText(mail);
             }
             con.close();
             
         }
         catch(Exception ex){
            System.out.println(ex.getMessage());;
         }

    }
}
